### ISSUE TITLE
run failed when import openai

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-chat#1]
```
Traceback (most recent call last):
  File "/Users/milochen/anaconda3/envs/pynecone-chat/bin/pc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/pynecone/pc.py", line 126, in run
    app = prerequisites.get_app()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 105, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/git/pynecone-chat/webui/webui/webui.py", line 3, in <module>
    from webui.state import State
  File "/Users/milochen/git/pynecone-chat/webui/webui/state.py", line 2, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
```

**Comment by milochen0418** [comment]
Solved by 
- https://github.com/pynecone-io/pynecone-chat/pull/2
