### ISSUE TITLE
openai.error.InvalidRequestError: The model `gpt-3.5` does not exist

### ISSUE THREAD

**Issue by biosopher** [pynecone-io/pynecone-chat#9]
Just cloned the repo and getting this error:

App running at: http://localhost:3000
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Traceback (most recent call last):
  File "/Users/anthonystevens/miniconda3/envs/genai/lib/python3.11/site-packages/reflex/state.py", line 737, in _process_event
    async for event in events:
  File "/Users/anthonystevens/Documents/Development/GitHub/reflex-chat/webui/webui/state.py", line 106, in process_question
    session = openai.ChatCompletion.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/miniconda3/envs/genai/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/miniconda3/envs/genai/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/miniconda3/envs/genai/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/miniconda3/envs/genai/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/Users/anthonystevens/miniconda3/envs/genai/lib/python3.11/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-3.5` does not exist

**Comment by picklelo** [comment]
Just merged in #8 to update the model - please reopen if you still have this issue!
